paths:
  data_folder: "data/raw"
  file_names:
    - "workshop.txt"
    - "rerun.txt"
    - "overall.txt"
  faiss_index: "artifacts/faiss_product_index"

models:
  embedding: "text-embedding-3-small"
  llm: "gpt-3.5-turbo"

retriever:
  search_type: "similarity"
  k_value: 4
 
# Reference to prompt template file
prompt_config:
  template_name: "sales_support"
  version: "v1"